export type Framework = {
  number: string;
  slug: string;
  title: string;
  category: string;
  enterpriseLayer: string;
  theme: string;
  tagline: string;
  thesis: string;
  statuses: string[];
  links: {
    detail: string;
    demo: string;
    github: string;
    substack?: string;
    linkedin?: string;
  };
};

export const frameworks: Framework[] = [
  {
    number: "Framework 01",
    slug: "womens-health-longitudinal-dashboard",
    title: "Women's Health Longitudinal Dashboard",
    category: "HealthTech / Patient Data",
    enterpriseLayer: "Patient-owned clinical context infrastructure",
    theme: "The data model is medicine. The export format is the appointment.",
    tagline: "Patient-owned. Longitudinal. Clinical-conversation-ready.",
    thesis: "The data model is medicine. The export format is the appointment.",
    statuses: ["Spec Ready", "Demo Live", "Repo Live"],
    links: {
      detail: "/frameworks/womens-health-longitudinal-dashboard",
      demo: "/frameworks/womens-health-longitudinal-dashboard/demo",
      github: "https://github.com/thehustleisholy-ship-it/thihsystems-frameworks",
      substack: "https://substack.com/@michaelmartinthih",
      linkedin: "https://www.linkedin.com/company/124453928/admin/dashboard/",
    },
  },
  {
    number: "Framework 02",
    slug: "job-loss-income-shock-stabilizer",
    title: "Job-Loss & Income-Shock Stabilizer",
    category: "Workforce Transition Infrastructure",
    enterpriseLayer: "Workforce transition continuity",
    theme: "The first 30 days after income loss determine the next 3 years.",
    tagline: "30-day stabilization operating system for income loss.",
    thesis: "The first 30 days after job loss determine the next 3 years. The difference between stabilization and spiral is often whether someone receives a structured Day 1 operating plan.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/job-loss-income-shock-stabilizer",
      demo: "/frameworks/job-loss-income-shock-stabilizer/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-02-job-loss-income-shock-stabilizer",
    },
  },
  {
    number: "Framework 03",
    slug: "returning-citizen-reentry-roadmap",
    title: "Returning Citizen Reentry Roadmap",
    category: "Justice-to-Stability Infrastructure",
    enterpriseLayer: "Reentry service coordination",
    theme: "Freedom without infrastructure becomes another trap.",
    tagline: "Reentry stability coordination and documentation system.",
    thesis: "Freedom without infrastructure becomes another trap. Reentry fails when documentation, housing, employment, transportation, compliance, and support are treated as separate problems.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/returning-citizen-reentry-roadmap",
      demo: "/frameworks/returning-citizen-reentry-roadmap/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-03-returning-citizen-reentry-roadmap",
    },
  },
  {
    number: "Framework 04",
    slug: "black-maternal-health-emergency-response-system",
    title: "Black Maternal Health Emergency Response System",
    category: "Maternal Risk Escalation Infrastructure",
    enterpriseLayer: "Maternal red-flag escalation and advocacy",
    theme: "Being dismissed can become deadly.",
    tagline: "Red-flag escalation system for maternal safety.",
    thesis: "Being dismissed can become deadly. Maternal risk needs an escalation system before symptoms are minimized, delayed, or normalized.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/black-maternal-health-emergency-response-system",
      demo: "/frameworks/black-maternal-health-emergency-response-system/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-04-black-maternal-health-emergency-response-system",
    },
  },
  {
    number: "Framework 05",
    slug: "hospital-grid-independence-resilience",
    title: "Hospital Grid-Independence & Resilience Framework",
    category: "Critical Facility Continuity",
    enterpriseLayer: "Critical facility continuity infrastructure",
    theme: "A hospital that cannot survive grid failure is not resilient care.",
    tagline: "72-hour hospital continuity and grid-independence planning.",
    thesis: "A hospital that cannot survive grid failure is not resilient care. Continuity must be tested across power, fuel, water, oxygen, staffing, pharmacy, communications, and access routes.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/hospital-grid-independence-resilience",
      demo: "/frameworks/hospital-grid-independence-resilience/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-05-hospital-grid-independence-resilience",
    },
  },
  {
    number: "Framework 06",
    slug: "eviction-defense-documentation-system",
    title: "Eviction Defense Documentation System",
    category: "Housing Stability Infrastructure",
    enterpriseLayer: "Housing stability documentation infrastructure",
    theme: "Most people do not lose housing because they had no case; they lose because they had no system.",
    tagline: "Evidence vault and court-prep system for housing defense.",
    thesis: "Most people do not lose housing because they had no case. They lose because they had no system.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/eviction-defense-documentation-system",
      demo: "/frameworks/eviction-defense-documentation-system/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-06-eviction-defense-documentation-system",
    },
  },
  {
    number: "Framework 07",
    slug: "phosphorus-recovery-circular-fertilizer",
    title: "Phosphorus Recovery & Circular Fertilizer Framework",
    category: "Nutrient Security Infrastructure",
    enterpriseLayer: "Strategic nutrient recovery infrastructure",
    theme: "We are flushing food security into the ocean.",
    tagline: "Nutrient recovery and circular fertilizer production system.",
    thesis: "We are flushing food security into the ocean. Phosphorus is essential to agriculture, geographically concentrated, and routinely wasted through wastewater and runoff.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/phosphorus-recovery-circular-fertilizer",
      demo: "/frameworks/phosphorus-recovery-circular-fertilizer/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-07-phosphorus-recovery-circular-fertilizer",
    },
  },
  {
    number: "Framework 08",
    slug: "sand-crisis-alternative-aggregate",
    title: "Sand Crisis & Alternative Aggregate Supply Chain",
    category: "Construction Material Resilience",
    enterpriseLayer: "Construction aggregate risk and substitution infrastructure",
    theme: "The world is running out of the sand modern life is built on.",
    tagline: "Aggregate supply risk and material substitution framework.",
    thesis: "The world is running out of the sand modern life is built on. Construction resilience requires aggregate visibility, substitution pathways, and recycled material planning.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/sand-crisis-alternative-aggregate",
      demo: "/frameworks/sand-crisis-alternative-aggregate/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-08-sand-crisis-alternative-aggregate",
    },
  },
  {
    number: "Framework 09",
    slug: "topsoil-regeneration-no-till-transition",
    title: "Topsoil Regeneration & No-Till Transition Accelerator",
    category: "Soil-Capital Preservation",
    enterpriseLayer: "Soil-health transition infrastructure",
    theme: "Soil is not dirt. It is civilization's savings account.",
    tagline: "Soil transition planning and regeneration accelerator.",
    thesis: "Soil is not dirt. It is civilization's savings account. Regeneration requires transition planning, not slogans.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/topsoil-regeneration-no-till-transition",
      demo: "/frameworks/topsoil-regeneration-no-till-transition/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-09-topsoil-regeneration-no-till-transition",
    },
  },
  {
    number: "Framework 10",
    slug: "managed-aquifer-recharge-water-banking",
    title: "Managed Aquifer Recharge & Underground Water Banking",
    category: "Water Security Infrastructure",
    enterpriseLayer: "Aquifer recharge, drought resilience, and underground water banking",
    theme: "Groundwater collapse is invisible until the wells run dry.",
    tagline: "Underground water banking and drought resilience system.",
    thesis: "Groundwater collapse is invisible until the wells run dry. Managed recharge turns water abundance in one season into stored resilience for another.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Pending"],
    links: {
      detail: "/frameworks/managed-aquifer-recharge-water-banking",
      demo: "/frameworks/managed-aquifer-recharge-water-banking/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-10-managed-aquifer-recharge-water-banking",
    },
  },
  {
    number: "Framework 11",
    slug: "gps-failure-contingency-backup-navigation",
    title: "GPS Failure Contingency & Backup Navigation Infrastructure",
    category: "Fragile Systems",
    enterpriseLayer: "Positioning, navigation, and timing resilience",
    theme: "Modern civilization forgot how dependent it is on invisible signals.",
    tagline: "GPS dependency and backup navigation resilience system.",
    thesis: "Modern civilization forgot how dependent it is on invisible signals. GPS failure cascades across systems: supply chains, emergency response, financial markets, and critical infrastructure.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/gps-failure-contingency-backup-navigation",
      demo: "/frameworks/gps-failure-contingency-backup-navigation/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-11-gps-failure-contingency-backup-navigation",
    },
  },
  {
    number: "Framework 12",
    slug: "pediatric-neurodevelopmental-journey-map",
    title: "Pediatric Neurodevelopmental Journey Map",
    category: "Children & Development",
    enterpriseLayer: "Early intervention evidence and care coordination",
    theme: "Early intervention depends on evidence parents are rarely equipped to organize.",
    tagline: "Early developmental screening and intervention coordination system.",
    thesis: "Early intervention depends on evidence parents are rarely equipped to organize. Developmental milestones, referral pathways, and clinical coordination are scattered across pediatrics, schools, and therapy.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/pediatric-neurodevelopmental-journey-map",
      demo: "/frameworks/pediatric-neurodevelopmental-journey-map/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-12-pediatric-neurodevelopmental-journey-map",
    },
  },
  {
    number: "Framework 13",
    slug: "strategic-grain-reserve-local-food-security",
    title: "Strategic Grain Reserve & Local Food Security Buffer",
    category: "Food Security",
    enterpriseLayer: "Regional food continuity infrastructure",
    theme: "A city with three days of food is not secure.",
    tagline: "Local food buffer and grain reserve planning system.",
    thesis: "A city with three days of food is not secure. Regional food continuity requires strategic grain reserves, local production capacity, and supply chain resilience planning.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/strategic-grain-reserve-local-food-security",
      demo: "/frameworks/strategic-grain-reserve-local-food-security/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-13-strategic-grain-reserve-local-food-security",
    },
  },
  {
    number: "Framework 14",
    slug: "parole-probation-compliance-tracker",
    title: "Parole & Probation Compliance Tracker",
    category: "Justice & Reentry",
    enterpriseLayer: "Supervision compliance and technical-violation prevention",
    theme: "Technical violations should not become revolving doors.",
    tagline: "Compliance calendar and requirement tracking system.",
    thesis: "Technical violations should not become revolving doors. Parole and probation compliance requires clear deadline tracking, requirement coordination, and escalation prevention.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/parole-probation-compliance-tracker",
      demo: "/frameworks/parole-probation-compliance-tracker/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-14-parole-probation-compliance-tracker",
    },
  },
  {
    number: "Framework 15",
    slug: "chronic-pain-evidence-journal",
    title: "Chronic Pain Evidence Journal",
    category: "Patient-Owned Health",
    enterpriseLayer: "Longitudinal symptom evidence and clinical preparation",
    theme: "Pain should not have to become performance art to be believed.",
    tagline: "Chronic pain evidence collection and visit preparation system.",
    thesis: "Pain should not have to become performance art to be believed. Chronic pain patients need structured evidence collection to prepare clinicians and prevent dismissal.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/chronic-pain-evidence-journal",
      demo: "/frameworks/chronic-pain-evidence-journal/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-15-chronic-pain-evidence-journal",
    },
  },
  {
    number: "Framework 16",
    slug: "trades-workforce-pipeline-apprenticeship",
    title: "Trades Workforce Pipeline & Apprenticeship Rebuild",
    category: "Work & Production",
    enterpriseLayer: "Skilled labor infrastructure",
    theme: "The infrastructure boom cannot happen without the hands to build it.",
    tagline: "Regional trades talent pipeline and apprenticeship system.",
    thesis: "The infrastructure boom cannot happen without the hands to build it. Trades workforce requires evidence-based pipeline planning, apprenticeship coordination, and regional capacity mapping.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/trades-workforce-pipeline-apprenticeship",
      demo: "/frameworks/trades-workforce-pipeline-apprenticeship/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-16-trades-workforce-pipeline-apprenticeship",
    },
  },
  {
    number: "Framework 17",
    slug: "asylum-evidence-documentation-builder",
    title: "Asylum Evidence & Documentation Builder",
    category: "Immigration & Displacement",
    enterpriseLayer: "Protection evidence organization and case-prep infrastructure",
    theme: "A person fleeing danger should not lose protection because their evidence was scattered.",
    tagline: "Asylum case evidence organization and documentation system.",
    thesis: "A person fleeing danger should not lose protection because their evidence was scattered. Asylum cases depend on organized evidence, timeline documentation, and legal-prep infrastructure.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/asylum-evidence-documentation-builder",
      demo: "/frameworks/asylum-evidence-documentation-builder/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-17-asylum-evidence-documentation-builder",
    },
  },
  {
    number: "Framework 18",
    slug: "pollinator-collapse-buffer-alternative-pollination",
    title: "Pollinator Collapse Buffer & Alternative Pollination Framework",
    category: "Ecological Tipping Points",
    enterpriseLayer: "Crop pollination risk and food-system resilience",
    theme: "The smallest workers hold up the food system.",
    tagline: "Crop pollination risk and habitat resilience system.",
    thesis: "The smallest workers hold up the food system. Pollinator collapse threatens food security. Regional resilience requires habitat mapping, alternative pollination planning, and risk assessment.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/pollinator-collapse-buffer-alternative-pollination",
      demo: "/frameworks/pollinator-collapse-buffer-alternative-pollination/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-18-pollinator-collapse-buffer-alternative-pollination",
    },
  },
  {
    number: "Framework 19",
    slug: "copper-constraint-electrification-material-flow",
    title: "Copper Constraint & Electrification Material Flow Framework",
    category: "Energy Transition Materials",
    enterpriseLayer: "Electrification material intelligence",
    theme: "You cannot electrify the future without accounting for the metal.",
    tagline: "Copper demand, substitution, and electrification planning system.",
    thesis: "You cannot electrify the future without accounting for the metal. Electrification requires copper supply visibility, substitution pathways, and material flow intelligence.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/copper-constraint-electrification-material-flow",
      demo: "/frameworks/copper-constraint-electrification-material-flow/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-19-copper-constraint-electrification-material-flow",
    },
  },
  {
    number: "Framework 20",
    slug: "distributed-manufacturing-local-production-network",
    title: "Distributed Manufacturing & Local Production Network",
    category: "Supply Chain Resilience",
    enterpriseLayer: "Regional production capacity and critical goods resilience",
    theme: "Efficiency without resilience is just fragility with better branding.",
    tagline: "Local manufacturing capacity and critical goods resilience system.",
    thesis: "Efficiency without resilience is just fragility with better branding. Regional resilience requires visibility into local production capacity, critical goods mapping, and distributed manufacturing planning.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/distributed-manufacturing-local-production-network",
      demo: "/frameworks/distributed-manufacturing-local-production-network/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-20-distributed-manufacturing-local-production-network",
    },
  },
  {
    number: "Framework 21",
    slug: "kinship-care-grandfamily-support-infrastructure",
    title: "Kinship Care Grandfamily Support Infrastructure",
    category: "Family & Care Burdens",
    enterpriseLayer: "Informal caregiver support and benefits navigation",
    theme: "Grandparents are raising children inside systems that do not see them as parents.",
    tagline: "Kinship care support and documentation system.",
    thesis: "Grandparents are raising children inside systems that do not see them as parents. Kinship caregivers need benefits navigation, legal documentation, and formal support infrastructure.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/kinship-care-grandfamily-support-infrastructure",
      demo: "/frameworks/kinship-care-grandfamily-support-infrastructure/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-21-kinship-care-grandfamily-support-infrastructure",
    },
  },
  {
    number: "Framework 22",
    slug: "ocean-dead-zone-reversal-hypoxia-recovery",
    title: "Ocean Dead Zone Reversal & Hypoxia Recovery Framework",
    category: "Ecological Recovery",
    enterpriseLayer: "Watershed-to-coast nutrient reduction and fisheries recovery",
    theme: "The runoff upstream becomes the silence underwater.",
    tagline: "Nutrient runoff reduction and hypoxia recovery system.",
    thesis: "The runoff upstream becomes the silence underwater. Dead zones require watershed-wide nutrient management, agricultural runoff reduction, and coastal habitat recovery.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/ocean-dead-zone-reversal-hypoxia-recovery",
      demo: "/frameworks/ocean-dead-zone-reversal-hypoxia-recovery/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-22-ocean-dead-zone-reversal-hypoxia-recovery",
    },
  },
  {
    number: "Framework 23",
    slug: "elder-financial-abuse-detection-response",
    title: "Elder Financial Abuse Detection & Response System",
    category: "Aging & Protection",
    enterpriseLayer: "Financial exploitation detection and response coordination",
    theme: "Exploitation often wears the face of someone trusted.",
    tagline: "Elder financial risk detection and response system.",
    thesis: "Exploitation often wears the face of someone trusted. Elder financial abuse requires early detection systems, coordinated response, and protective documentation.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/elder-financial-abuse-detection-response",
      demo: "/frameworks/elder-financial-abuse-detection-response/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-23-elder-financial-abuse-detection-response",
    },
  },
  {
    number: "Framework 24",
    slug: "domestic-violence-exit-safety-documentation",
    title: "Domestic Violence Exit & Safety Documentation System",
    category: "Safety & Abuse Response",
    enterpriseLayer: "Survivor safety planning and evidence documentation",
    theme: "Leaving safely is not one decision; it is an infrastructure problem.",
    tagline: "Survivor safety planning and evidence documentation system.",
    thesis: "Leaving safely is not one decision; it is an infrastructure problem. Survivors need comprehensive safety planning, evidence documentation, and coordinated response infrastructure.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/domestic-violence-exit-safety-documentation",
      demo: "/frameworks/domestic-violence-exit-safety-documentation/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-24-domestic-violence-exit-safety-documentation",
    },
  },
  {
    number: "Framework 25",
    slug: "solar-wind-end-of-life-recovery-framework",
    title: "Solar Panel & Wind Turbine End-of-Life Recovery Framework",
    category: "Circular Economy",
    enterpriseLayer: "Renewable asset recovery and material circularity",
    theme: "Solving one crisis should not create the next waste crisis.",
    tagline: "Renewable asset end-of-life recovery system.",
    thesis: "Solving one crisis should not create the next waste crisis. Renewable asset recovery requires material tracking, circularity planning, and end-of-life infrastructure.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/solar-wind-end-of-life-recovery-framework",
      demo: "/frameworks/solar-wind-end-of-life-recovery-framework/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-25-solar-wind-end-of-life-recovery-framework",
    },
  },
  {
    number: "Framework 26",
    slug: "school-to-prison-pipeline-disruption",
    title: "School-to-Prison Pipeline Disruption Framework",
    category: "Youth & Justice",
    enterpriseLayer: "School discipline escalation prevention and youth protection",
    theme: "Some children are disciplined into systems they should have been protected from.",
    tagline: "School discipline intervention and youth protection system.",
    thesis: "Some children are disciplined into systems they should have been protected from. Pipeline disruption requires discipline data transparency, intervention pathways, and institutional accountability.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/school-to-prison-pipeline-disruption",
      demo: "/frameworks/school-to-prison-pipeline-disruption/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-26-school-to-prison-pipeline-disruption",
    },
  },
  {
    number: "Framework 27",
    slug: "intercity-rail-revival-sleeper-train-network",
    title: "Intercity Rail Revival & Sleeper Train Network",
    category: "Mobility & Public Infrastructure",
    enterpriseLayer: "Regional passenger mobility and corridor planning",
    theme: "A serious country should move people without making every trip a punishment.",
    tagline: "Regional rail and sleeper train network planning system.",
    thesis: "A serious country should move people without making every trip a punishment. Rail revival requires corridor planning, sleeper network design, and regional coordination.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/intercity-rail-revival-sleeper-train-network",
      demo: "/frameworks/intercity-rail-revival-sleeper-train-network/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-27-intercity-rail-revival-sleeper-train-network",
    },
  },
  {
    number: "Framework 28",
    slug: "human-lifespan-extension-longevity-society",
    title: "Human Lifespan Extension & Longevity Society Framework",
    category: "Future Governance",
    enterpriseLayer: "Institutional planning for longer lives",
    theme: "If longer life is coming, society must prepare before only the wealthy inherit time.",
    tagline: "Longevity impact and institutional readiness system.",
    thesis: "If longer life is coming, society must prepare before only the wealthy inherit time. Longevity governance requires institutional planning, equity frameworks, and public preparation.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/human-lifespan-extension-longevity-society",
      demo: "/frameworks/human-lifespan-extension-longevity-society/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-28-human-lifespan-extension-longevity-society",
    },
  },
  {
    number: "Framework 29",
    slug: "solar-geoengineering-governance-framework",
    title: "Solar Geoengineering Governance Framework",
    category: "Planetary Risk Governance",
    enterpriseLayer: "Pre-deployment governance, moratorium, and public consent infrastructure",
    theme: "Governance must precede deployment.",
    tagline: "Solar geoengineering governance and moratorium system.",
    thesis: "Governance must precede deployment. Geoengineering requires pre-deployment governance frameworks, public consent infrastructure, and planetary accountability.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/solar-geoengineering-governance-framework",
      demo: "/frameworks/solar-geoengineering-governance-framework/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-29-solar-geoengineering-governance-framework",
    },
  },
  {
    number: "Framework 30",
    slug: "orbital-debris-tracking-collision-governance",
    title: "Orbital Debris Tracking & Collision Governance Framework",
    category: "Space Infrastructure Continuity",
    enterpriseLayer: "Orbital commons risk management and collision accountability",
    theme: "One collision can turn orbit into a minefield.",
    tagline: "Orbital debris risk and collision governance system.",
    thesis: "One collision can turn orbit into a minefield. Orbital safety requires debris tracking, collision prevention governance, and commons accountability frameworks.",
    statuses: ["Concept Structured", "Demo Preview", "Repo Ready"],
    links: {
      detail: "/frameworks/orbital-debris-tracking-collision-governance",
      demo: "/frameworks/orbital-debris-tracking-collision-governance/demo",
      github: "https://github.com/thehustleisholy-ship-it/framework-30-orbital-debris-tracking-collision-governance",
    },
  },
];

// Backward compatibility: export Framework 01 data for existing routes
export const framework = frameworks[0];
export const links = frameworks[0].links;

// Framework 01 demo data
export const phaseHeatmap = [
  { symptom: "Pain", menstrual: 8, follicular: 3, ovulation: 4, luteal: 7 },
  { symptom: "Fatigue", menstrual: 7, follicular: 3, ovulation: 4, luteal: 8 },
  { symptom: "Mood shift", menstrual: 5, follicular: 2, ovulation: 3, luteal: 7 },
  { symptom: "Sleep disruption", menstrual: 6, follicular: 2, ovulation: 3, luteal: 6 },
  { symptom: "Digestive", menstrual: 5, follicular: 2, ovulation: 2, luteal: 5 },
];

export const timeline = [
  {
    date: "Cycle 18, day 23",
    title: "Luteal fatigue spike",
    note: "Energy dropped below baseline for four consecutive evenings.",
  },
  {
    date: "Cycle 19, day 2",
    title: "Pain intensity changed",
    note: "Pain moved from intermittent to sustained during first 36 hours.",
  },
  {
    date: "Cycle 20, day 14",
    title: "Mid-cycle sleep shift",
    note: "Sleep interruptions clustered near ovulation window.",
  },
];

export const insights = [
  "Symptoms cluster most reliably in the late luteal and early menstrual phases.",
  "Fatigue and pain rise together in two of the last three cycles.",
  "Sleep disruption appears before the highest symptom days, making it useful for visit prep.",
];

