import type { Metadata } from "next";
import Link from "next/link";

const demo = "/frameworks/asylum-evidence-documentation-builder/demo";
export const metadata: Metadata = {
  title: "Framework 17: Asylum Evidence & Documentation Builder",
  description: "A proposed, synthetic framework for organizing chronology, source provenance, translation needs, unresolved conflicts, and questions for qualified counsel.",
  alternates: { canonical: "/frameworks/asylum-evidence-documentation-builder" },
  openGraph: { title: "Framework 17: Asylum Evidence & Documentation Builder", description: "When the truth is real but the record is incomplete.", url: "/frameworks/asylum-evidence-documentation-builder", type: "article", images: [{ url: "/framework-17/open-graph.png", width: 1200, height: 630, alt: "Dark green and amber Framework 17 title card with connected evidence and provenance nodes." }] },
  twitter: { card: "summary_large_image", title: "Framework 17: Asylum Evidence & Documentation Builder", description: "When the truth is real but the record is incomplete.", images: ["/framework-17/open-graph.png"] },
};
function Arrow() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4" fill="none"><path d="M5 12h14m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function Action({ href, children, primary = false }: { href: string; children: React.ReactNode; primary?: boolean }) {
  const cn = primary ? "focus-ring gold-button inline-flex min-h-12 items-center justify-center gap-2 rounded-md px-5 text-center text-sm font-semibold transition motion-reduce:transition-none hover:-translate-y-px motion-reduce:hover:translate-y-0" : "focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-md border hairline bg-white/[0.03] px-5 text-center text-sm font-semibold text-white transition motion-reduce:transition-none hover:border-[#d8b25a]/60 hover:bg-white/[0.06]";
  return <Link className={cn} href={href}>{children}<Arrow /></Link>;
}
function Section({ id, label, title, children }: { id?: string; label: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-8 border-b hairline py-12 sm:py-16"><div className="shell max-w-5xl"><p className="font-mono text-xs uppercase tracking-[0.16em] gold-text">{label}</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold leading-tight text-white sm:text-4xl">{title}</h2><div className="mt-6 text-base leading-7 silver-text">{children}</div></div></section>;
}
const sources = [
  ["S1", "USCIS · Form I-589 Instructions", "Corroboration, unavailable-evidence explanations, and certified English translations.", "https://www.uscis.gov/sites/default/files/document/forms/i-589instr.pdf"],
  ["S2", "8 CFR 208.13(a)", "Burden of proof and the contextual role of credible testimony.", "https://www.law.cornell.edu/cfr/text/8/208.13"],
  ["S3", "DOJ EOIR · Representation guidance", "Who may provide representation and legal advice before EOIR.", "https://www.justice.gov/eoir/can-someone-represent-you-eoir"],
  ["S6", "Khan, Kuhn & Haque (2021)", "Systematic review describing heterogeneous trauma and autobiographical-memory findings.", "https://pmc.ncbi.nlm.nih.gov/articles/PMC8211731/"],
  ["S7", "Herlihy et al. (2002)", "Limited repeated-interview study examining discrepancies in asylum accounts.", "https://pmc.ncbi.nlm.nih.gov/articles/PMC65293/"],
] as const;

export default function Page() { return <main>
  <section className="border-b hairline py-7 sm:py-9"><div className="shell max-w-6xl">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link className="focus-ring text-sm gold-text" href="/">Back to Framework Fridays</Link><span className="rounded-full border border-emerald-300/30 bg-emerald-300/10 px-3 py-1 font-mono text-xs uppercase tracking-[0.12em] text-emerald-200">Interactive Illustration Live</span></div>
    <div className="mt-7 grid gap-7 lg:grid-cols-[1.35fr_.65fr] lg:items-end"><div><p className="font-mono text-sm uppercase tracking-[0.16em] gold-text">Framework 17</p><h1 className="mt-3 max-w-4xl text-4xl font-semibold leading-[1.06] text-white sm:text-5xl lg:text-6xl">When the Truth Is Real but the Record Is Incomplete</h1><p className="mt-4 text-xl font-semibold text-white sm:text-2xl">Asylum Evidence &amp; Documentation Builder</p><p className="mt-4 max-w-3xl text-base leading-7 silver-text sm:text-lg">A proposed preparation framework for organizing user-confirmed chronology, source provenance, translation needs, unresolved conflicts, and questions for qualified counsel—without manufacturing a cleaner story.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Action href={demo} primary>Try the Interactive Illustration</Action><Action href="#research-sources">Review the Research &amp; Sources</Action></div></div>
    <aside className="rounded-lg border border-amber-200/20 bg-amber-100/[0.04] p-5 text-sm leading-6 text-secondary" aria-label="Illustration boundaries"><strong className="text-white">No uploads. No accounts. Synthetic data only.</strong> This illustration does not determine eligibility, assess credibility, generate testimony, or provide legal advice.</aside></div>
    <div className="mt-7 grid gap-3 border-t hairline pt-5 text-sm sm:grid-cols-2"><p><span className="muted-text">Category</span><br /><span className="silver-text">Immigration &amp; Displacement</span></p><p><span className="muted-text">Enterprise Layer</span><br /><span className="silver-text">Protection evidence organization and case-prep infrastructure</span></p></div>
  </div></section>
  <Section label="The human pain" title="A lived experience can be truthful while its supporting record remains incomplete."><p className="max-w-3xl">A person fleeing danger should not lose the opportunity to communicate their experience because the supporting record became scattered. Records may sit across devices, accounts, languages, countries, or trusted contacts; some dates may remain approximate or unknown.</p></Section>
  <Section label="Documented evidence" title="The process asks people to manage evidence, absence, and translation."><div className="grid gap-5 md:grid-cols-2"><p>Current Form I-589 instructions address reasonably available corroborative evidence, explanations when evidence is unavailable, and certified English translations of foreign-language documents. These are process facts, not proof that completeness equals truth. <a className="focus-ring gold-text" href="#source-s1">[S1]</a></p><p>Peer-reviewed findings on trauma, mental health, and autobiographical memory are heterogeneous. A discrepancy alone is not proof of fabrication. <a className="focus-ring gold-text" href="#source-s6">[S6]</a> <a className="focus-ring gold-text" href="#source-s7">[S7]</a></p></div></Section>
  <Section label="Proposed framework" title="Preserve uncertainty instead of treating it as a software defect."><p className="max-w-3xl">The proposed framework inventories sources, marks dates as exact, approximate, unknown, or conflicted, queues translation work, records person-authored explanations for unavailable evidence, and prepares unresolved questions for qualified review. Its design aspiration is to help people retain the opportunity to communicate their experience; it is not evidence that the framework improves legal outcomes.</p></Section>
  <Section label="AI role · Human boundary" title="AI may organize. It must never adjudicate, invent, or coach."><div className="grid gap-5 md:grid-cols-2"><article className="metal-panel rounded-lg p-5"><h3 className="font-semibold text-white">AI could assist with</h3><p className="mt-3">Classifying user-confirmed items, flagging empty provenance fields, identifying translation queues, surfacing conflicts without resolving them, and formatting a person-approved inventory.</p></article><article className="metal-panel rounded-lg p-5"><h3 className="font-semibold text-white">People retain authority</h3><p className="mt-3">Only the person confirms facts. Qualified practitioners interpret law. Human interpreters and translators preserve meaning. Software must not determine eligibility, assess credibility, generate testimony, fill gaps, advise, predict, or file.</p></article></div></Section>
  <Section label="Data model" title="Separate the record, the uncertainty, and the review decision."><ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Chronology events", "Evidence items and provenance", "Translation tasks", "Visible conflicts", "Legal-review questions", "Export consent and safety gate"].map((item) => <li key={item} className="rounded-md border hairline bg-white/[0.03] p-4 text-white">{item}</li>)}</ul></Section>
  <Section label="Assumptions and limitations" title="A researched proposal is not a validated legal product."><p className="max-w-3xl">The illustration is deterministic and synthetic. It does not accept names, narratives, documents, or contact information. It does not read narrative meaning or map facts to asylum law. A real continuation would require participatory governance, threat modeling, consent, access controls, encryption, retention and deletion rules, safe-device guidance, accessibility testing, and qualified legal and privacy review.</p></Section>
  <Section label="Open questions" title="What still needs correction before any real-world continuation?"><ul className="list-disc space-y-2 pl-5"><li>Which secure-device and retention model works across different threat contexts?</li><li>How should witness information be minimized while preserving provenance?</li><li>Which prompts avoid pressuring people to retell trauma?</li><li>Can categorization preserve meaning across languages, dialects, calendars, and transliterations?</li><li>What works for low literacy, cognitive load, intermittent connectivity, and mobile-only access?</li></ul></Section>
  <Section id="research-sources" label="Research and sources" title="Claims are bounded by a public source register."><p className="mb-6 max-w-3xl">Reviewed July 17, 2026. Legal rules can change; verify the governing forum, current form edition, deadlines, and case-specific requirements with qualified counsel.</p><div className="space-y-3">{sources.map(([id, name, note, href]) => <article id={`source-${id.toLowerCase()}`} key={id} className="scroll-mt-8 rounded-lg border hairline bg-white/[0.03] p-5"><p className="font-mono text-xs gold-text">{id}</p><h3 className="mt-1 font-semibold text-white">{name}</h3><p className="mt-2 text-sm">{note}</p><a className="focus-ring mt-3 inline-flex text-sm gold-text" href={href} target="_blank" rel="noreferrer">Open source <span className="sr-only">: {name}</span></a></article>)}</div></Section>
  <Section label="Related frameworks · Build record" title="Continue through the wider systems library or inspect the work."><div className="grid gap-5 md:grid-cols-2"><article className="metal-panel rounded-lg p-5"><h3 className="font-semibold text-white">Related frameworks</h3><p className="mt-3">Explore adjacent work on identity, public systems, health, and institutional readiness in the Framework Fridays research dashboard.</p><Link className="focus-ring mt-4 inline-flex gold-text" href="/research">Return to the Research Dashboard</Link></article><article className="metal-panel rounded-lg p-5"><h3 className="font-semibold text-white">Build record</h3><p className="mt-3">The public repository contains the specification, source register, claims ledger, data schemas, privacy architecture, test plan, synthetic scenarios, and release record.</p><a className="focus-ring mt-4 inline-flex gold-text" href="https://github.com/thehustleisholy-ship-it/framework-17-asylum-evidence-documentation-builder" target="_blank" rel="noreferrer">Review the build repository</a></article></div></Section>
  <section id="participate" className="py-12 sm:py-16"><div className="shell max-w-5xl rounded-xl border hairline bg-white/[0.03] p-6 sm:p-8"><p className="font-mono text-xs uppercase tracking-[0.16em] gold-text">Help improve the proposal</p><h2 className="mt-3 text-3xl font-semibold text-white">Lived experience and professional correction are welcome.</h2><p className="mt-4 max-w-3xl leading-7 silver-text">People with lived experience, immigration attorneys, accredited representatives, interpreters, advocates, trauma researchers, accessibility specialists, and privacy or security practitioners are invited to correct the claims, language, boundaries, and data model.</p><p className="mt-4 max-w-3xl rounded-md border border-amber-200/20 bg-amber-100/[0.04] p-4 text-sm leading-6 text-secondary"><strong className="text-white">Protect your privacy:</strong> do not disclose names, case numbers, immigration details, legal documents, or sensitive personal information publicly.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Action href={demo} primary>Try the Interactive Illustration</Action><Action href="/research">Return to the Research Dashboard</Action><Action href="mailto:hello@thihsystems.com?subject=Framework%2017%20correction">Help Improve This Framework</Action></div></div></section>
</main>; }
